---
branches:
- "[0-9]+.[0-9]+.x"
- name: "main"
  prerelease: "rc"
repositoryUrl: https://github.com/philipp-hinteregger/semantic-release-test.git
tagFormat: "${version}"
plugins:
- "@semantic-release/commit-analyzer"
- "@semantic-release/release-notes-generator"
- "@semantic-release/github"